const getFolderColor = (name = "") => {
  const key = name.toLowerCase();

  const map = {
    src: "text-sky-300",
    public: "text-emerald-300",
    assets: "text-violet-300",
    components: "text-blue-300",
    pages: "text-amber-300",
    layouts: "text-indigo-300",
    hooks: "text-purple-300",
    utils: "text-cyan-300",
    lib: "text-slate-300",
    services: "text-teal-300",
    api: "text-sky-300",
    redux: "text-violet-300",
    store: "text-purple-300",
    context: "text-indigo-300",
    styles: "text-pink-300",
    css: "text-blue-300",
    images: "text-emerald-300",
    icons: "text-amber-300",
    fonts: "text-stone-300",
    tests: "text-green-300",
    __tests__: "text-green-300",
    node_modules: "text-slate-500",

    backend: "text-emerald-300",
    frontend: "text-sky-300",
    routes: "text-indigo-300",
    controllers: "text-amber-300",
    models: "text-violet-300",
    middleware: "text-teal-300",
    config: "text-slate-300",
    database: "text-cyan-300",
    migrations: "text-orange-300",
    uploads: "text-emerald-300",
    logs: "text-stone-300",

    app: "text-sky-300",
    features: "text-violet-300",
    constants: "text-amber-300",
    helpers: "text-cyan-300",
    types: "text-blue-300",
    interfaces: "text-indigo-300",
    validators: "text-rose-300",
    schemas: "text-purple-300",
    providers: "text-teal-300",
    workers: "text-orange-300",
    jobs: "text-amber-300",
    queues: "text-rose-300",
    events: "text-fuchsia-300",
    sockets: "text-emerald-300",
    graphql: "text-pink-300",
    prisma: "text-indigo-300",
    supabase: "text-emerald-300",
    firebase: "text-amber-300",
    mongodb: "text-green-300",
    redis: "text-rose-300",
    postgres: "text-sky-300",
    docs: "text-slate-300",
    examples: "text-lime-300",
    scripts: "text-orange-300",
    tools: "text-slate-300",
    build: "text-orange-300",
    dist: "text-slate-500",
    coverage: "text-green-300",
    e2e: "text-purple-300",
    integration: "text-indigo-300",
    unit: "text-blue-300",
    mocks: "text-pink-300",
    fixtures: "text-teal-300",
    cache: "text-amber-300",
    auth: "text-rose-300",
    payments: "text-emerald-300",
    notifications: "text-amber-300",
    templates: "text-violet-300",
    microservices: "text-indigo-300",
    gateway: "text-cyan-300",
    shared: "text-blue-300",
    common: "text-slate-300",
    packages: "text-orange-300",
    plugins: "text-purple-300",
    extensions: "text-sky-300",
    infra: "text-cyan-300",
    infrastructure: "text-cyan-300",
    deployment: "text-emerald-300",
    docker: "text-sky-300",
    kubernetes: "text-indigo-300",
    monitoring: "text-amber-300",
    metrics: "text-orange-300",
    security: "text-rose-300",
    docs: "text-slate-300",
    ".github": "text-slate-300",
    ".vscode": "text-sky-300",
    ".husky": "text-orange-300",
  };

  return map[key] || "text-zinc-400";
};

export default getFolderColor;